buildscript {
    ext {
        vXnat = "1.8.2-SNAPSHOT"
    }
    repositories {
        mavenLocal()
        maven { url "https://plugins.gradle.org/m2" }
        mavenCentral()
        jcenter()
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    }
    dependencies {
        gradleApi()
        classpath "io.franzbecker:gradle-lombok:4.0.0"
        classpath "org.nrg.xnat.build:xnat-data-builder:${vXnat}"
    }
}

apply plugin: "java"
apply plugin: "maven-publish"
apply plugin: "eclipse"
apply plugin: "io.franzbecker.gradle-lombok"
apply plugin: "xnat-data-builder"

group "org.nrg.xnatx.plugins"
version "0.5.0-SNAPSHOT"

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenLocal()
    maven { url "https://dcm4che.org/maven2" }
    mavenCentral()
    jcenter()
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
}

configurations.all {
    exclude group: "javax.sql"
    exclude group: "javax.transaction"
    exclude group: "javax.jms"
}

dependencies {
    implementation platform("org.nrg:parent:${vXnat}")

    // Even though container-service plugin version is specified in the parent
    // BOM, it needs to be added here because the copyPlugins task in docker-compose
    // won't resolve it properly against the BOM.
    implementation "org.nrg.xnatx.plugins:container-service:3.0.0-SNAPSHOT:fat"

    implementation "org.nrg.xnat:web"
    implementation "io.springfox:springfox-swagger2"
}

task sourceJar(type: Jar, dependsOn: classes) {
    classifier "sources"
    from sourceSets.main.allSource
}

task javadocJar(type: Jar) {
    classifier "javadoc"
    from javadoc.destinationDir
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifacts {
                artifact sourceJar
                artifact javadocJar
            }

            pom.withXml {
                def root = asNode()
                root.appendNode("name", "XNAT Batch Launch Plugin")
                root.appendNode("url", "https://bitbucket.org/xnatx/xnatx-batch-launch-plugin")
                root.appendNode("inceptionYear", "2019")

                root.appendNode("scm").with {
                    appendNode("url", "https://bitbucket.org/xnatx/xnatx-batch-launch-plugin")
                    appendNode("connection", "scm:https://bitbucket.org/xnatx/xnatx-batch-launch-plugin")
                    appendNode("developerConnection", "scm:git@bitbucket.org:xnatx/xnatx-batch-launch-plugin.git")
                }

                root.appendNode("licenses").appendNode("license").with {
                    appendNode("name", "Simplified BSD 2-Clause License")
                    appendNode("url", "https://xnat.org/about/license.php")
                    appendNode("distribution", "repo")
                }

                root.appendNode("developers").with {
                    appendNode("developer").with {
                        appendNode("id", "mohana")
                        appendNode("name", "Mohana Ramaratnam")
                        appendNode("email", "mohana@radiologics.com")
                    }
                }
            }
        }
    }
    repositories {
        maven {
            credentials {
                // These properties must be set in the ~/.gradle/gradle.properties file or passed on the Gradle command
                // line in the form -PrepoUsername=foo -PrepoPassword=bar.
                username propertyWithDefault("repoUsername", "username")
                password propertyWithDefault("repoPassword", "password")
            }
            if (project.version.endsWith("-SNAPSHOT")) {
                url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot-local"
            } else {
                url "https://nrgxnat.jfrog.io/nrgxnat/libs-release-local"
            }
        }
    }
}

def propertyWithDefault(String name, Object value) {
    hasProperty(name) ? property(name) : value
}
