#Batch launch logging
log4j.category.org.nrg.xnat.bulk=DEBUG, batchLaunch
log4j.additivity.org.nrg.xnat.bulk=false
log4j.appender.batchLaunch = org.apache.log4j.DailyRollingFileAppender
log4j.appender.batchLaunch.DatePattern='.'yyy-MM-dd
log4j.appender.batchLaunch.file = ${xnat.home}/logs/batchLaunch.log
log4j.appender.batchLaunch.layout = org.apache.log4j.PatternLayout
log4j.appender.batchLaunch.layout.conversionPattern = %d [%t] %-5p %c - %m%n
log4j.appender.batchLaunch.append = true
